### ISSUE TITLE
User Story: Client authentication

### ISSUE THREAD

**Issue by jordancodurance** [codurance/academy-september-2021#15]
Estimated T-Shirt size: Medium

### Description

**In order to** authenticate with the client
**As a** user
**I would like to** consent to using my codurance account

### Acceptance Criteria

**Scenario 1** 
**Given** I am logged into my codurance account
  **When**  Click the login button
**Then** I should be logged into the client and see my name relating to my codurance account

**Scenario 2** 
**Given** I am logged into my codurance account
**and** the authentication failed
  **When**  Click the login button
**Then** I should be given feedback on why it failed

**Scenario 3** 
**Given** I am not logged into my codurance account
  **When**  Click the login button
**Then** I should be given the oppurtunity to log in to my codurance account

### Tech Analysis
**As a** developer
**I want** to implement authenitcated routes with the google authentication library
**This will require** authenitcation guards
**This will depend on** valid google authentication token being stored locally

**Comment by niall-bambury-codurance** [comment]
As product owner this ticket has been reviewed and accepted
